### ISSUE TITLE
General - user name assignment - Part 2 - not urgent 

### ISSUE THREAD

**Issue by Collabophotos** [nautilusdigital/collabo-issues#13]
Can you please change use name associated to 604-889-7973 to Kris instead of spongebob and for number 236-998-9198, please change to Varun? If you are not able to change, then just reassign the user names to a dummy number so that they will need to re-enter their user name again when logging in.

For allowing special characters, special characters is not allowed as first letter. Also no profanity allow for user names.  Anything that would be deemed inappropriate.

Here is a preliminary list of user names that we would like blocked in addition to trademark names which I'm sure there must be a database somewhere. 

@Naz - please add to the list for any user names you want to make unavailable

Anything that has Collabo in the name.  Just thinking of future if we have corporate accounts etc. that we could use Collabo in front of whatever the company name is so that its always something everyone can see. examples - Collabophotos / Collabo.events / Collabo-gallery

Personal blocks:
JChiang
J.Chiang
J-Chiang
J_Chiang
JasonChiang
Jason.Chiang
Jason_Chiang
Jason-Chiang

Peterpanisaninja
Peterpan
Suma

Krisco
KrisSutherland
Kris.Sutherland
Kris_Sutherland
Kris-Sutherland
Suds
Krissuds
Kriso808

**Comment by mhousser** [comment]
@Collabophotos `kris` and `varun` usernames have been changed in **production** environment.

**Comment by Collabophotos** [comment]
Thank you.
