### ISSUE TITLE
Update 'selected thumbnail checkmark' to the green check circle used in iOS photo uploads

### ISSUE THREAD

**Issue by mhousser** [nautilusdigital/collabo-issues#18]
The tiny check box is impossible to see. Need to use the 'green circle w/ check mark' in the following areas:

- [x] Android: Download photo thumb screen
- [x] Android: Upload photo thumb screen
- [x] iOS: Download photo thumb screen

**Comment by robsonmic** [comment]
@vivanov1410  My latest build on Android is still showing the skinny icons. (v39)
